/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedChildrenIndexRouteImport } from './routes/_authenticated/children.index'
import { Route as AuthenticatedChildrenChildIdRouteImport } from './routes/_authenticated/children.$childId'
import { Route as AuthenticatedChildrenNewRouteImport } from './routes/_authenticated/children.new'
import { Route as AuthenticatedChildrenChildIdEditRouteImport } from './routes/_authenticated/children.$childId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChildrenIndexRoute =
  AuthenticatedChildrenIndexRouteImport.update({
    id: '/children/',
    path: '/children/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChildrenChildIdRoute =
  AuthenticatedChildrenChildIdRouteImport.update({
    id: '/children/$childId',
    path: '/children/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChildrenNewRoute =
  AuthenticatedChildrenNewRouteImport.update({
    id: '/children/new',
    path: '/children/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChildrenChildIdEditRoute =
  AuthenticatedChildrenChildIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedChildrenChildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/children/$childId': typeof AuthenticatedChildrenChildIdRouteWithChildren
  '/children/new': typeof AuthenticatedChildrenNewRoute
  '/children/': typeof AuthenticatedChildrenIndexRoute
  '/children/$childId/edit': typeof AuthenticatedChildrenChildIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/children/$childId': typeof AuthenticatedChildrenChildIdRouteWithChildren
  '/children/new': typeof AuthenticatedChildrenNewRoute
  '/children': typeof AuthenticatedChildrenIndexRoute
  '/children/$childId/edit': typeof AuthenticatedChildrenChildIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/children/$childId': typeof AuthenticatedChildrenChildIdRouteWithChildren
  '/_authenticated/children/new': typeof AuthenticatedChildrenNewRoute
  '/_authenticated/children/': typeof AuthenticatedChildrenIndexRoute
  '/_authenticated/children/$childId/edit': typeof AuthenticatedChildrenChildIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/administration'
    | '/calendar'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/children/$childId'
    | '/children/new'
    | '/children/'
    | '/children/$childId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/administration'
    | '/calendar'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/children/$childId'
    | '/children/new'
    | '/children'
    | '/children/$childId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/activities'
    | '/_authenticated/administration'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/children/$childId'
    | '/_authenticated/children/new'
    | '/_authenticated/children/'
    | '/_authenticated/children/$childId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children/': {
      id: '/_authenticated/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof AuthenticatedChildrenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children/$childId': {
      id: '/_authenticated/children/$childId'
      path: '/children/$childId'
      fullPath: '/children/$childId'
      preLoaderRoute: typeof AuthenticatedChildrenChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children/new': {
      id: '/_authenticated/children/new'
      path: '/children/new'
      fullPath: '/children/new'
      preLoaderRoute: typeof AuthenticatedChildrenNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children/$childId/edit': {
      id: '/_authenticated/children/$childId/edit'
      path: '/edit'
      fullPath: '/children/$childId/edit'
      preLoaderRoute: typeof AuthenticatedChildrenChildIdEditRouteImport
      parentRoute: typeof AuthenticatedChildrenChildIdRoute
    }
  }
}

interface AuthenticatedChildrenChildIdRouteChildren {
  AuthenticatedChildrenChildIdEditRoute: typeof AuthenticatedChildrenChildIdEditRoute
}

const AuthenticatedChildrenChildIdRouteChildren: AuthenticatedChildrenChildIdRouteChildren =
  {
    AuthenticatedChildrenChildIdEditRoute:
      AuthenticatedChildrenChildIdEditRoute,
  }

const AuthenticatedChildrenChildIdRouteWithChildren =
  AuthenticatedChildrenChildIdRoute._addFileChildren(
    AuthenticatedChildrenChildIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChildrenChildIdRoute: typeof AuthenticatedChildrenChildIdRouteWithChildren
  AuthenticatedChildrenNewRoute: typeof AuthenticatedChildrenNewRoute
  AuthenticatedChildrenIndexRoute: typeof AuthenticatedChildrenIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedAdministrationRoute: AuthenticatedAdministrationRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChildrenChildIdRoute:
    AuthenticatedChildrenChildIdRouteWithChildren,
  AuthenticatedChildrenNewRoute: AuthenticatedChildrenNewRoute,
  AuthenticatedChildrenIndexRoute: AuthenticatedChildrenIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
